#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
apt:
 preserve_sources_list: true

packages:
 - python3
#  - nginx

runcmd:
#  - [ systemctl, reload, nginx ]
#  - [ systemctl, enable, nginx.service ]
#  - [ systemctl, start, --no-block, nginx.service ]
  # - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) > /var/www/html/index.html" ]
