- name: Install gnupg, apt-transport-https
  apt: 
    name: apt-transport-https,gnupg
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Download filebeat
  get_url:  
    url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.4.1-amd64.deb
    dest: /home/debian/

- name: Install filebeat
  apt:
    deb: /home/debian/filebeat-7.4.1-amd64.deb 

- name: Systemctl daemon reload
  systemd:
    daemon_reload: true
    name: filebeat.service
    state: started

- name: Filebeat configuration file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0600
    owner: root
    group: root

- name: Systemctl enable filebeat
  systemd:
    name: filebeat.service
    state: restarted