---
- import_tasks: ngnx.yml

- import_tasks: preflight.yml

- import_tasks: install.yml

- import_tasks: node_exporter.yml

- import_tasks: filebeat.yml

- name: Ensure Nginxlog Exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: nginxlog_exporter
    enabled: true
