---
- name: Install Nginx Web Server on Debian Family
  apt: name=nginx
    state=latest

- systemd:
    name: nginx
    enabled: yes
    state: started

- name: check for service nginx status
  shell: service nginx status
  ignore_errors: true
  register: nginxstatus

- name: Show service nginx service status
  debug:
    msg: "nginxstatus exists."
  when: nginxstatus.rc | int == 0

- name: Put to the index.html HOST name
  shell:
    cmd: sh -c "echo $(hostname | cut -d '.' -f 1 ) > /var/www/html/index.nginx-debian.html"

- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Change access.log permissions
  file:
    path: /var/log/nginx/access.log
    mode: '0644'