---
- name: Install gnupg, apt-transport-https
  apt: 
    name: apt-transport-https,gnupg
    state: present
    update_cache: yes
    cache_valid_time: 3600

# - name: Download Java
#   get_url: 
#     url: https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
#     dest: /home/debian/

# - name: Install Java
#   apt:
#     deb: /home/debian/jdk-17_linux-x64_bin.deb

- name: Download Elasticsearch 7.4.1 
  get_url:  
    url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.4.1-amd64.deb
    dest: /home/debian/

- name: Install elasticsearch
  apt:
    deb: /home/debian/elasticsearch-7.4.1-amd64.deb

- name: Systemctl daemon reload
  systemd:
    daemon_reload: true
    name: elasticsearch.service
    state: started

- name: Copy config file for elasticsearch
  copy:
    src: ./elasticsearch/files/elasticsearch.yml
    dest: /etc/elasticsearch
    mode: 0660
    owner: root
    group: elasticsearch 

- name: Systemctl enable elasticsearch 
  systemd:
    name: elasticsearch.service
    state: restarted

# - name: Set up pswd for Elasticsearch
#   shell: /usr/share/elasticsearch/bin/elasticsearch-users useradd admin -p administrator -r superuser

# - name: Generate token For kibana
#   shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
#   register: kibana_token
  
# - name: Show kibana_token
#   debug: var=kibana_token.stdout_lines