---

- name: restart nginxlog_exporter
  systemd:
    daemon_reload: true
    name: nginxlog_exporter
    state: restarted

- name: restart nginx
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted

- name: reload_daemon_and_restart_node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
